name: Lint Code Base

on: pull_request

permissions:
  contents: read

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter@v6.3.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_KUBERNETES_KUBECONFORM: false
          VALIDATE_GITLEAKS: false
          VALIDATE_YAML: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # copied from https://github.com/renovatebot/helm-charts
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and run helm-docs
        run: |-
          mkdir ./.bin
          export PATH="./.bin:$PATH"
          # renovate: datasource=github-releases depName=helm-docs packageName=norwoodj/helm-docs
          HELM_DOCS_VERSION=1.13.1

          # install helm-docs
          curl --silent --show-error --fail --location --output /tmp/helm-docs.tar.gz https://github.com/norwoodj/helm-docs/releases/download/v"${HELM_DOCS_VERSION}"/helm-docs_"${HELM_DOCS_VERSION}"_Linux_x86_64.tar.gz
          tar -C .bin/ -xf /tmp/helm-docs.tar.gz helm-docs

          .github/helm-docs.sh
      - name: Check dirty state
        run: git diff --exit-code
