name: Renovate
on:
  schedule:
    - cron: "0 * * * 3"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.JENKINS_DEPENDENCY_UPDATER_APP_ID }}
          private_key: ${{ secrets.JENKINS_DEPENDENCY_UPDATER_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: 🏗 Set up yq
        uses: frenck/action-setup-yq@v1.0.2

      - name: next release version
        id: nextversion
        uses: jenkins-x-plugins/jx-release-version@v2.7.1
        with:
          previous-version: from-file:charts/jenkins/Chart.yaml

      - name: Set up Helm
        id: helm
        uses: azure/setup-helm@v3
        with:
          # renovate: datasource=github-tags depName=helm/helm
          version: v3.12.0

      - name: install helm unittests
        run: |
          helm env
          helm plugin install https://github.com/helm-unittest/helm-unittest --version 0.3.6

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        with:
          token: "${{ steps.get_token.outputs.token }}"
          docker-volumes: |
            /tmp:/tmp ;
            ${{ steps.helm.outputs.helm-path }}:/usr/bin/helm ;
            ${{ env.HELM_PLUGINS }}/helm-unittest:/usr/bin/helm-plugins/helm-unittest ;
            ${{ env.RUNNER_TEMP }}/yq/yq:/usr/bin/yq ;
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|HELM_PLUGINS|NEXT_VERSION)$"
        env:
          HELM_PLUGINS: "/bin/helm-plugins"
          NEXT_VERSION: ${{ steps.nextversion.outputs.version }}
