{{- if .Values.controller.initScripts -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jenkins.fullname" . }}-init-scripts
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    {{- include "jenkins.commonlabels" . | nindent 4 }}
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
data:
{{- range $key, $val := .Values.controller.initScripts }}
  init{{ $key }}.groovy: |-
{{ tpl $val $ | indent 4 }}
{{- end }}
{{- end }}
