{{- if or .Values.controller.userContents .Values.controller.binaryUserContents -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jenkins.fullname" . }}-user-contents
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ template "jenkins.label" .}}"
    {{- end }}
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
data:
{{- range .Values.controller.userContents }}
  {{ .name }}: |-
{{ .data | indent 4 }}
{{- end }}
binaryData:
{{- range .Values.controller.binaryUserContents }}
  {{ .name }}: {{ .data }}
{{- end }}
{{- end }}
