{{- if .Values.checkDeprecation }}
   {{- if .Values.master }}
      {{ fail "`master` does no longer exist. It has been renamed to `controller`" }}
   {{- end }}

   {{- if .Values.NetworkPolicy }}

      {{- if .Values.NetworkPolicy.Enabled }}
         {{ fail "`NetworkPolicy.Enabled` does no longer exist. It has been renamed to `networkPolicy.enabled`" }}
      {{- end }}

      {{- if .Values.NetworkPolicy.ApiVersion }}
         {{ fail "`NetworkPolicy.ApiVersion` does no longer exist. It has been renamed to `networkPolicy.apiVersion`" }}
      {{- end }}

      {{ fail "NetworkPolicy.* values have been renamed, please check the documentation" }}
   {{- end }}


   {{- if .Values.rbac.install }}
      {{ fail "`rbac.install` does no longer exist. It has been renamed to `rbac.create` and is enabled by default!" }}
   {{- end }}

   {{- if .Values.rbac.serviceAccountName }}
      {{ fail "`rbac.serviceAccountName` does no longer exist. It has been renamed to `serviceAccount.name`" }}
   {{- end }}

   {{- if .Values.rbac.serviceAccountAnnotations }}
      {{ fail "`rbac.serviceAccountAnnotations` does no longer exist. It has been renamed to `serviceAccount.annotations`" }}
   {{- end }}

   {{- if .Values.rbac.roleRef }}
      {{ fail "`rbac.roleRef` does no longer exist. RBAC roles are now generated, please check the documentation" }}
   {{- end }}

   {{- if .Values.rbac.roleKind }}
      {{ fail "`rbac.roleKind` does no longer exist. RBAC roles are now generated, please check the documentation" }}
   {{- end }}

   {{- if .Values.rbac.roleBindingKind }}
      {{ fail "`rbac.roleBindingKind` does no longer exist. RBAC roles are now generated, please check the documentation" }}
   {{- end }}

   {{- if .Values.controller.JCasC.pluginVersion }}
      {{ fail "controller.JCasC.pluginVersion has been deprecated, please use controller.installPlugins instead" }}
   {{- end }}

   {{- if .Values.controller.deploymentLabels }}
   {{ fail "`controller.deploymentLabels` does no longer exist. It has been renamed to `controller.statefulSetLabels`" }}
   {{- end }}

   {{- if .Values.controller.deploymentAnnotations }}
   {{ fail "`controller.deploymentAnnotations` does no longer exist. It has been renamed to `controller.statefulSetAnnotations`" }}
   {{- end }}

   {{- if .Values.controller.rollingUpdate }}
   {{ fail "`controller.rollingUpdate` does no longer exist. It is no longer relevant, since a StatefulSet is used for the Jenkins controller" }}
   {{- end }}
{{- end }}
