apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins.fullname" . }}-agent
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
{{- if .Values.controller.slaveListenerServiceAnnotations }}
  annotations:
{{ toYaml .Values.controller.slaveListenerServiceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - port: {{ .Values.controller.slaveListenerPort }}
      targetPort: {{ .Values.controller.slaveListenerPort }}
      {{ if (and (eq .Values.controller.slaveListenerServiceType "NodePort") (not (empty .Values.controller.slaveListenerPort))) }}
      nodePort: {{.Values.controller.slaveListenerPort}}
      {{end}}
      name: slavelistener
  selector:
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
  type: {{ .Values.controller.slaveListenerServiceType }}
  {{  if eq .Values.controller.slaveListenerServiceType "LoadBalancer"  }}
  {{  if .Values.controller.slaveListenerLoadBalancerIP  }}
  loadBalancerIP: {{  .Values.controller.slaveListenerLoadBalancerIP  }}
  {{end}}
  {{end}}
