{{- $kubeTargetVersion := default .Capabilities.KubeVersion.GitVersion .Values.kubeTargetVersionOverride }}
{{- if .Values.controller.secondaryingress.enabled }}
{{- if semverCompare ">=1.19-0" $kubeTargetVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $kubeTargetVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: {{ .Values.controller.secondaryingress.apiVersion }}
{{- end }}
kind: Ingress
metadata:
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ template "jenkins.label" .}}"
    {{- end }}
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
{{- if .Values.controller.secondaryingress.labels }}
{{ toYaml .Values.controller.secondaryingress.labels | indent 4 }}
{{- end }}
{{- if .Values.controller.secondaryingress.annotations }}
  annotations:
{{ toYaml .Values.controller.secondaryingress.annotations | indent 4 }}
{{- end }}
  name: {{ template "jenkins.fullname" . }}-secondary
spec:
{{- if .Values.controller.secondaryingress.ingressClassName }}
  ingressClassName: {{ .Values.controller.secondaryingress.ingressClassName | quote }}
{{- end }}
  rules:
  - http:
      paths:
{{- if empty (.Values.controller.secondaryingress.paths) }}
      - backend:
{{- if semverCompare ">=1.19-0" $kubeTargetVersion }}
          service:
            name: {{ template "jenkins.fullname" . }}
            port:
              number: {{ .Values.controller.servicePort }}
        pathType: ImplementationSpecific
{{- else }}
          serviceName: {{ template "jenkins.fullname" . }}
          servicePort: {{ .Values.controller.servicePort }}
{{- end }}
{{- if .Values.controller.secondaryingress.path }}
        path: {{ .Values.controller.secondaryingress.path }}
{{- end -}}
{{- else }}
{{ tpl (toYaml .Values.controller.secondaryingress.paths | indent 6) . }}
{{- end -}}
{{- if .Values.controller.secondaryingress.hostName }}
    host: {{ .Values.controller.secondaryingress.hostName | quote }}
{{- end }}
{{- if .Values.controller.secondaryingress.resourceRootUrl }}
  - http:
      paths:
      - backend:
{{- if semverCompare ">=1.19-0" $kubeTargetVersion }}
          service:
            name: {{ template "jenkins.fullname" . }}
            port:
              number: {{ .Values.controller.servicePort }}
        pathType: ImplementationSpecific
{{- else }}
          serviceName: {{ template "jenkins.fullname" . }}
          servicePort: {{ .Values.controller.servicePort }}
{{- end }}
    host: {{ .Values.controller.secondaryingress.resourceRootUrl | quote }}
{{- end }}
{{- if .Values.controller.secondaryingress.tls }}
  tls:
{{ toYaml .Values.controller.secondaryingress.tls | indent 4 }}
{{- end -}}
{{- end }}
