{{- if .Values.controller.secretClaims -}}
{{- $r := .Release -}}
{{- $v := .Values -}}
{{- $chart := printf "%s-%s" .Chart.Name .Chart.Version -}}
{{- $namespace := include "jenkins.namespace" . -}}
{{- $serviceName := include "jenkins.fullname" . -}}
{{ range .Values.controller.secretClaims }}
---
kind: SecretClaim
apiVersion: vaultproject.io/v1
metadata:
  name: {{ $serviceName }}-{{ .name | default .path | lower }}
  namespace: {{ $namespace }}
  labels:
    {{- include "jenkins.commonlabels" . | nindent 4 }}
    "app.kubernetes.io/component": "{{ $v.controller.componentName }}"
spec:
  type: {{ .type | default "Opaque" }}
  path: {{ .path }}
{{- if .renew }}
  renew: {{ .renew }}
{{- end }}
{{- end }}
{{- end }}
