{{- if .Values.controller.additionalSecrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}-additional-secrets
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    {{- include "jenkins.commonlabels" . | nindent 4 }}
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
type: Opaque
data:
{{- range .Values.controller.additionalSecrets }}
  {{ .name }}: {{ .value | b64enc }}
{{- end }}
{{- end }}
