{{- if and (not .Values.controller.admin.existingSecret) (.Values.controller.adminSecret) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    {{- include "jenkins.commonlabels" . | nindent 4 }}
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
type: Opaque
data:
  jenkins-admin-password: {{ template "jenkins.password" . }}
  jenkins-admin-user: {{ .Values.controller.adminUser | b64enc | quote }}
{{- end }}
