{{- if and (not .Values.master.admin.existingSecret) (.Values.master.useSecurity) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.master.componentName }}"
type: Opaque
data:
  {{ if .Values.master.adminPassword -}}
  ADMIN_PASSWORD: {{ .Values.master.adminPassword | b64enc | quote }}
  {{ else -}}
  ADMIN_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end -}}
  ADMIN_USER: {{ .Values.master.adminUser | b64enc | quote }}
{{- end }}
